name: Print File Content CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print hello_world.txt content
        run: cat hello_world.txt
